### ISSUE TITLE
JQuery Component

### ISSUE THREAD

**Issue by arcphysx** [erdkse/adminlte-3-vue#20]
Hi! I just started a new project using this setup. I wonder how do I call a component that requires Jquery in AdminLTE, such as Toasts? Thank you in advance

**Comment by erdkse** [comment]
This project is not meant to work with JQuery. If you want to use toast you can use some 3rd party library that supports Vue 3. Otherwise, I will implement it in the project whenever I find free time. You can use it at that time.
