### ISSUE TITLE
automatic width and position ... dropdown-menu

### ISSUE THREAD

**Issue by sten-stulda** [erdkse/adminlte-3-vue#23]
Hallo,

I can't find it anywhere 

Toggle device toolbar for iPhone 5/SE (320x568)

in adminlte.io example by click dropdown-menu ... is added style -> style="left: inherit; right: -113px;"

in erdkse/adminlte-3-vue by click dropdown-menu ... do not add none style

**Comment by erdkse** [comment]
Working on #24 ..
