### ISSUE TITLE
tag nav

### ISSUE THREAD

**Issue by sten-stulda** [erdkse/adminlte-3-vue#26]
Navbar does not work properly in lower resolutions

**Comment by erdkse** [comment]
Please add a screenshot. I don't see any problem.

**Comment by cn-2k** [comment]
> Please add a screenshot. I don't see any problem.

The problem is that sidebar doesn't show up when you toggle it in mobile devices.

**Comment by cn-2k** [comment]
> > Please add a screenshot. I don't see any problem.
> 
> The problem is that sidebar doesn't show up when you toggle it in mobile devices.

Sorry for spam, I've checked that sidebar dont close when you click outside too.

**Comment by sten-stulda** [comment]
Sorry, no navbar but sidebar 

before click 
![error](https://user-images.githubusercontent.com/11896172/134851201-f859f314-c5d1-4d22-a3d7-a8e89134b954.PNG)

after click
![error2](https://user-images.githubusercontent.com/11896172/134851236-3f0e1d90-d507-433f-bf6b-6b7c13be0cd0.PNG)

**Comment by erdkse** [comment]
Ok will check it this weekend.
