### ISSUE TITLE
Dark mode/side bar implementation

### ISSUE THREAD

**Issue by olufemioyedepo** [erdkse/adminlte-3-vue#30]
Great work so far @erdkse,
It would be nice the template can have a dark mode toggle as shown in the screenshot below from the base template.

![adminlte-sidebar-darkmode](https://user-images.githubusercontent.com/19518859/142008976-bc414751-e8e8-4c10-93d0-0a3332627f56.PNG)

**Comment by olufemioyedepo** [comment]
Hi @erdkse

**Comment by erdkse** [comment]
Hey @olufemioyedepo ! Will work on this one on weekend

**Comment by erdkse** [comment]
@olufemioyedepo`darkMode` is added to `src/store/ui/index.ts` file. You can set its value there.

**Comment by olufemioyedepo** [comment]
@erdkse great job so far but how can the user toggle the dark mode?

**Comment by erdkse** [comment]
They can't currently. Ok I will add that too

**Comment by olufemioyedepo** [comment]
Ok great Erdi

**Comment by erdkse** [comment]
Work in progress. You can follow up by visiting the related PR.

**Comment by erdkse** [comment]
@olufemioyedepo Done!

**Comment by olufemioyedepo** [comment]
Great job Erdi!
