### ISSUE TITLE
error cannot find module './util/root'

### ISSUE THREAD

**Issue by bernardo-campos** [erdkse/adminlte-3-vue#32]
I made 
`git clone ...`
then
`npm install`
and after a while I got the error "cannot find module './util/root'"

I'm using npm version 7.23.0

**Comment by erdkse** [comment]
Can you share the full error log, please?

**Comment by bernardo-campos** [comment]
5122 verbose stack Error: command failed
5122 verbose stack     at ChildProcess.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
5122 verbose stack     at ChildProcess.emit (events.js:315:20)
5122 verbose stack     at maybeClose (internal/child_process.js:1048:16)
5122 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
5123 verbose pkgid cypress@3.8.3
5124 verbose cwd E:\Proyectos\tests\adminlte-3-vue
5125 verbose Windows_NT 10.0.19042
5126 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myuser\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
5127 verbose node v14.16.0
5128 verbose npm  v7.23.0
5129 error code 1
5130 error path E:\Proyectos\tests\adminlte-3-vue\node_modules\cypress
5131 error command failed
5132 error command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
5133 error internal/modules/cjs/loader.js:883
5133 error   throw err;
5133 error   ^
5133 error
5133 error Error: Cannot find module './util/root'
5133 error Require stack:
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\node_modules\rxjs\Observable.js
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\node_modules\rxjs\Subject.js
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\lib\task.js
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\index.js
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\cypress\lib\tasks\install.js
5133 error - E:\Proyectos\tests\adminlte-3-vue\node_modules\cypress\index.js
5133 error     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
5133 error     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
5133 error     at Module.require (internal/modules/cjs/loader.js:952:19)
5133 error     at require (internal/modules/cjs/helpers.js:88:18)
5133 error     at Object.<anonymous> (E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\node_modules\rxjs\Observable.js:2:14)
5133 error     at Module._compile (internal/modules/cjs/loader.js:1063:30)
5133 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
5133 error     at Module.load (internal/modules/cjs/loader.js:928:32)
5133 error     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
5133 error     at Module.require (internal/modules/cjs/loader.js:952:19)
5133 error     at require (internal/modules/cjs/helpers.js:88:18)
5133 error     at Object.<anonymous> (E:\Proyectos\tests\adminlte-3-vue\node_modules\listr\node_modules\rxjs\Subject.js:7:20)
5133 error     at Module._compile (internal/modules/cjs/loader.js:1063:30)
5133 error     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
5133 error     at Module.load (internal/modules/cjs/loader.js:928:32)
5133 error     at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
5133 error   code: 'MODULE_NOT_FOUND',
5133 error   requireStack: [
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\listr\\node_modules\\rxjs\\Observable.js',
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\listr\\node_modules\\rxjs\\Subject.js',
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\listr\\lib\\task.js',
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\listr\\index.js',
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\cypress\\lib\\tasks\\install.js',
5133 error     'E:\\Proyectos\\tests\\adminlte-3-vue\\node_modules\\cypress\\index.js'
5133 error   ]
5133 error }
5134 verbose exit 1

**Comment by bernardo-campos** [comment]
I've uninstalled and installed npm. And now works. Idk why

**Comment by erdkse** [comment]
This looks like a dependency error. If you delete your`node_modules`, `package-lock.json` and do npm install again the problem probably will be solved. You don't have to delete npm completely :)

**Comment by bernardo-campos** [comment]
I tried both before but did not work

**Comment by erdkse** [comment]
I see - I am glad that It works now
