### ISSUE TITLE
Is there auth option without gatekeeper?

### ISSUE THREAD

**Issue by donakhseputa** [erdkse/adminlte-3-vue#36]
if we have an API gateway self how to use this template?

**Comment by erdkse** [comment]
Of course, there is - remove gatekeeper functions and add your own.

**Comment by donakhseputa** [comment]
> Of course, there is - remove gatekeeper functions and add your own.

If I want to remove gatekeeper, what files I must change? or can you show/give me example without gatekeeper?
or would be nice if you can make gatekeeper as optional authentication.. so people can setting in .env to config auth with gatekeeper or not?

**Comment by erdkse** [comment]
Currently not on my roadmap. But will consider it, thank you
