### ISSUE TITLE
Example CRUD

### ISSUE THREAD

**Issue by donakhseputa** [erdkse/adminlte-3-vue#37]
Hello, I'm very interested in your this repository.
can you add an example and documentation of how to create a CRUD page with this repo?
thanks.

**Comment by erdkse** [comment]
What do you mean bu CRUD page?

**Comment by donakhseputa** [comment]
how to implement RESTful API with your repo. For example, I want to add a menu called Article. 
I need a page that shows all articles with pagination, then I need a page that can show the form to add/update Articles. lastly, delete an article with a prompt popup. How to achieve these?

**Comment by erdkse** [comment]
Do you know VueJS?

**Comment by donakhseputa** [comment]
yeah, I know and still learning, but I don't know how to implement it into your repo. mostly what I learn from tutorials and your repo has a different structure. That's why I need your help.

**Comment by erdkse** [comment]
If you check `class components` for Vue It will help you
