### ISSUE TITLE
Dynamic sidebar menu

### ISSUE THREAD

**Issue by donakhseputa** [erdkse/adminlte-3-vue#38]
Hello, it is me again.
sorry if I have many requests from you.
How I can make a dynamic sidebar menu depend on the user's permissions?

**Comment by erdkse** [comment]
You can generate this MENU property depending on user permissions

https://github.com/erdkse/adminlte-3-vue/blob/main/src/modules/main/menu-sidebar/menu-sidebar.ts#L22

**Comment by donakhseputa** [comment]
How to set this menu depends on the user's permission? For example, an Admin will have a "User Management" menu and a basic User not have.
Sorry if I have so many questions, I'm a new learning vue. What I want is to create a dashboard that has login/logout function, a sidebar menu depend on the user's permission, and a complete CRUD page, which lists page using pagination. can you help me? I would great to thanks to you.

**Comment by erdkse** [comment]
You need to fetch user permissions before creating the menu and create the menu according to these permissions - and unfortunately creating a sample data page is not on my roadmap - I advise you to follow some documentation and tutorials - It is pretty straightforward thing.

**Comment by donakhseputa** [comment]
I have learned from tutorials, but what I learned and your repo has a different structure.
