### ISSUE TITLE
sidebar toggle not working

### ISSUE THREAD

**Issue by neotune** [erdkse/adminlte-3-vue#42]
first, thank you for the work

browser size 900 X 1217 
(helper.ts in calculateWindowSize function return value 'sm')
default sidebar is hidden
and toggle button click -> sidebar is showing 

clicking on content area Sidebar doesn't disappear

please tell me how to fix it

**Comment by erdkse** [comment]
I will check it as soon as possible, thank you for reporting

**Comment by erdkse** [comment]
Are you still having this problem?
