### ISSUE TITLE
Cannot find module 'eslint/use-at-your-own-risk'

### ISSUE THREAD

**Issue by rafa0128** [erdkse/adminlte-3-vue#44]
[eslint] Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » @vue/eslint-config-typescript/recommended » /Users/rafa/Documents/tech/github/adminlte-3-vue/node_modules/@vue/eslint-config-typescript/index.js': Cannot find module 'eslint/use-at-your-own-risk'

**Comment by erdkse** [comment]
are you still having this issue?

**Comment by erdkse** [comment]
It looks like the issue is not valid, closing the issue @rafa0128
