### ISSUE TITLE
i think you submitted your api credentials 

### ISSUE THREAD

**Issue by detain** [erdkse/adminlte-3-vue#48]
https://github.com/erdkse/adminlte-3-vue/blob/9c586ff9f2bc6fa42f4237a871a0ef05610541c6/src/utils/oidc-providers.ts
has
    client_id:
        'whatlooksliketobeyourapiaccountidfor.google.com',
    client_secret: 'thisislikelysomethingyoushouldnotsharewithothersorcommit',
i suggest removing or replaicing them with invalid creds... masked the original content for securititty

**Comment by erdkse** [comment]
It was on purpose but I will remove them, thank you for informing @detain
