### ISSUE TITLE
after build index.html blank page

### ISSUE THREAD

**Issue by simong782112** [erdkse/adminlte-3-vue#52]
Hi,

Your project AdminLTE3 with vue is very nice, i like it.

I have a problem that I can't solve, I'm asking for your help.

After npm run build command,  I tried call 'index.html' from 'dist' folder, but i got blank screen. Response is the next message:  "We're sorry but this website doesn't work properly without JavaScript enabled. Please enable it to continue." (www.mysystem.hu/vrestaurant)

In the browser the JavaScript is enabled, application has no errors, it runs on my local webserver over bitnami port.

What could be the problem, can you help me?

Thank you very much!

Simon Gábor

**Comment by erdkse** [comment]
Hey Simon, this question is not actually related with the repository itself. But as I see you are trying to serve your application under a sub path. You need to configure your server to handle requests under your desired path. This is the only thing that I can say about your problem. You may consider using some reverse proxy tools like nginx.
